language: python
python:
  - "2.7"
install:
  - pip install --quiet --requirement requirements.txt
script:
  - pycodestyle **/*.py
  - pylint **/*.py
  - coverage run --module unittest discover -p '*_test.py'
  - coverage report --show-missing --include='pipeline/*'
